# Configuration for SuperCraftBros by JRL1004
# Notice: This config is a work-in-progress and may need to be deleted if you update

# Set to 'false' to just use the "hard-coded" aspects of SCB
# for personal configuration, use 'true' then change the settings accordingly
useConfig: false

# Integer values (Numbers without decimals)
Integers:
  # Lives per player
  Lives: 3
  # Max players in a game
  maxPlayers: 10
  # Players needed for the game to start
  minPlayers: 2

# Booleans (true/false values)
# This feature is planned but not added
Booleans:
  # Allow players to 'queue' up for a game?
  Queuing: false
  # Allows players with permission to kick lower-ranked players from the game?
  VIPBoost: false
  # Enable use of the BarAPI?
  Bar-API: false

# String values (Basically anything you want the plugin to say within apostrophes ('')
# This feature is planned but not added
Strings:
  # What should the player see if they do not have permission for a class?
  No-Perm-Message: '&cYou do not have permission for this class'