name: SuperCraftBros
author: Double0negative
authors: [Double0negative, MCSG, JRL1004, mike1665]
version: 1.1
main: org.mcsg.double0negative.supercraftbros.SuperCraftBros
commands:
  scb:
    description: Super Craft Bros
    usage: /scb(command) (args)
    aliases: [scb]
depend: [WorldEdit]